- name: Create Local Repo | Get a list of all the files in /etc/yum.repos.d
  find:
    paths: /etc/yum.repos.d
    patterns: "*.repo"
  register: repo_files

- name: Create Local Repo | Remove files in /etc/yum.repos.d not redhat.repo
  file:
    path: "{{ item.path }}"
    state: absent
  when: item.path != "/etc/yum.repos.d/redhat.repo"
  with_items: "{{ repo_files.files }}"

- name: Create Local Repo | Create disconnected.repo
  file:
    path: /etc/yum.repos.d/disconnected.repo
    owner: root
    group: root
    mode: '0644'
    state: touch

- name: Create Local Repo | Populate disconnected repo
  blockinfile:
    path: /etc/yum.repos.d/disconnected.repo
    # yamllint disable rule:line-length
    block: |
      [rhel-7-server-rpms]
      baseurl = "{{ satellite_content_source }}/content/dist/rhel/server/7/7.7/x86_64/os/"
      name = Red Hat Enterprise Linux 7 Server (RPMs)
      enabled = 1
      gpgcheck = 0

      [rhel-7-server-satellite-{{ satellite_version }}-rpms]
      baseurl = "{{ satellite_content_source }}/content/dist/rhel/server/7/7Server/x86_64/satellite/{{ satellite_version }}/os/"
      name = Red Hat Satellite {{ satellite_version }} (for RHEL 7 Server) (RPMs)
      enabled = 1
      gpgcheck = 0

      [rhel-7-server-ansible-2.8-rpms]
      baseurl = "{{ satellite_content_source }}/content/dist/rhel/server/7/7Server/x86_64/ansible/2.8/os/"
      name = Red Hat Ansible Engine 2.8 RPMs for Red Hat Enterprise Linux 7 Server x86_64
      enabled = 1
      gpgcheck = 0

      [rhel-7-server-satellite-maintenance-6-rpms]
      baseurl = "{{ satellite_content_source }}/content/dist/rhel/server/7/7Server/x86_64/sat-maintenance/6/os/"
      name = Red Hat Satellite Maintenance 6 for RHEL 7 Server RPMs x86_64
      enabled = 1
      gpgcheck = 0

      [rhel-server-rhscl-7-rpms]
      baseurl = "{{ satellite_content_source }}/content/dist/rhel/server/7/7.7/x86_64/rhscl/1/os/"
      name = Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server x86_64 7Server
      enabled = 1
      gpgcheck = 0
    # yamllint enable
