# tasks file for rhsm
- name: main | rhsm subscribe
  import_tasks: 1_rhsm_subscribe.yml
  when: satellite_rhn_connect != 'disconnect'

- name: main | create local repo
  import_tasks: 2_create_local_repo.yml
  when: satellite_rhn_connect == 'disconnect'

- name: main | enable repo
  import_tasks: 3_enable_repo.yml
  when: satellite_rhn_connect != 'disconnect'
