- name: Main | Rhsm Subscribe
  import_tasks: 1_rhsm_subscribe.yml
  when: satellite_rhn_connect != 'disconnect'

- name: Main | Create Local Repo
  import_tasks: 2_create_local_repo.yml
  when: satellite_rhn_connect == 'disconnect'
