- name: "content views config | Create or update content views"
  katello_content_view:
    username: "{{ satellite_initial_admin_username }}"
    password: "{{ satellite_initial_admin_password }}"
    server_url: "{{ satellite_url }}"
    name: "{{ item.name }}"
    organization: "{{ satellite_initial_organization }}"
    repositories: "{{ item.repositories }}"
  with_items: "{{ satellite_content_views }}"
  notify: handler - publish content views

- meta: flush_handlers

- name: "config_content_views | Create a composite content view"
  katello_content_view:
    username: "{{ satellite_initial_admin_username }}"
    password: "{{ satellite_initial_admin_password }}"
    server_url: "{{ satellite_url }}"
    name: "{{ item.name }}"
    organization: "{{ satellite_foreman_initial_organization }}"
    composite: true
    auto_publish: true
    components: "{{ item.components }}"
  with_items: "{{ satellite_composite_content_views }}"
  notify: handler - publish composite content views

- meta: flush_handlers
