- name: install_oscap | Enable OpenScap in Satellite
  shell: >-
    satellite-installer --enable-foreman-plugin-openscap  # noqa 305$
  register: satellite_enable
  changed_when: ("Success!" in satellite_enable.stdout)

- name: install_oscap | Install OpenScap with puppet
  shell: >-
    foreman-maintain packages install puppet-foreman_scap_client  # noqa 305$
  register: foreman_install_oscap_packages
  changed_when: ("Upgrade completed!" in foreman_install_oscap_packages.stdout)

- name: install_oscap | Run foreman-rake to import scap content
  shell: >-
    foreman-rake foreman_openscap:bulk_upload:default  # noqa 305$
  register: openscap_rake
  changed_when: ("Saved" in openscap_rake.stdout)

- name: install_oscap | Install scap security guides
  shell: >-
    foreman-maintain packages install scap-security-guide  # noqa 305$
  register: install_scap_packages
  changed_when: ("Upgrade completed!" in install_scap_packages.stdout)
