# Handlers for satellite_config
- name: handler - publish content views
  katello_content_view_version:
    username: "{{ satellite_initial_admin_username }}"
    password: "{{ satellite_initial_admin_password }}"
    server_url: "{{ satellite_url }}"
    content_view: "{{ item.name }}"
    organization: "{{ satellite_initial_organization }}"
    lifecycle_environments:
      - Library
      - "{{ satellite_prod_lifecycle_env }}"
  with_items: "{{ satellite_content_views }}"

- name: handler - publish composite content views
  katello_content_view_version:
    username: "{{ satellite_initial_admin_username }}"
    password: "{{ satellite_initial_admin_password }}"
    server_url: "{{ satellite_url }}"
    content_view: "{{ item.name }}"
    organization: "{{ satellite_initial_organization }}"
    lifecycle_environments:
      - Library
      - "{{ satellite_prod_lifecycle_env }}"
  with_items: "{{ satellite_composite_content_views }}"

