- name: site | create satellite VM
  hosts: kvm
  become: false
  roles:
    - role: libvirt
  when: satellite_enable_virt

- name: site | snapshot satellite VM
  hosts: kvm
  become: false
  roles:
    - role: snapshot
      vars:
        vm: "{{ satellite_hostname }}"
        snap_name: "a-post-kickstart"
      when: satellite_enable_snap1

- name: site |  rhsm & yum update
  hosts: mgmt
  roles:
    - role: rhsm
    - role: yumupdate
  when: satellite_enable_rhsmyum

- name: site | snapshot satellite VM
  hosts: kvm
  become: false
  roles:
    - role: snapshot
      vars:
        vm: "{{ satellite_hostname }}"
        snap_name: "b-post-rhsm-and-yum-update"
      when: satellite_enable_snap2

- name: site | upload manifest, enable and sync content repos
  hosts: mgmt
  roles:
    - role: install
    - role: content
  when: satellite_enable_install_content

- name: site | snapshot satellite VM
  hosts: kvm
  become: false
  roles:
    - role: snapshot
      vars:
        vm: "{{ satellite_hostname }}"
        snap_name: "c-post-install-and-content"
      when: satellite_enable_snap3

- name: site | configure satellite
  hosts: mgmt
  roles:
    - role: config
  when: satellite_enable_config

- name: site | snapshot satellite VM
  hosts: kvm
  become: false
  roles:
    - role: snapshot
      vars:
        vm: "{{ satellite_hostname }}"
        snap_name: "d-post-satellite-config"
      when: satellite_enable_snap4
