# defaults file for sat_config
satellite_admin_username: "{{ lookup('env', 'SATELLITE_USERNAME') }}"
satellite_admin_password: "{{ lookup('env', 'SATELLITE_PASSWORD') }}"
satellite_organization: "{{ lookup('env', 'SATELLITE_ORGANIZATION') }}"
satellite_location: "{{ lookup('env', 'SATELLITE_LOCATION') }}"
satellite_version: "{{ lookup('env', 'SATELLITE_VERSION') }}"
satellite_fqdn: "{{ ansible_fqdn }}"
satellite_server_url: "https://{{ ansible_fqdn }}"
satellite_server_basearch: "x86_64"
satellite_prod_lifecycle_env: "Production"
satellite_domain: "{{ ansible_domain }}"
satellite_mgmtsubnet: "ManagementNetwork"
satellite_network: "{{ ansible_default_ipv4.network }}"
satellite_mask: "{{ ansible_default_ipv4.netmask }}"
satellite_dhcp_interface: "{{ ansible_default_ipv4.interface }}"  # eth0
satellite_dhcp_fromip: "192.168.122.100"
satellite_dhcp_toip: "192.168.122.150"
satellite_dhcp_range: "{{ satellite_dhcp_fromip }} {{ satellite_dhcp_toip }}"
satellite_dhcp_gateway: "{{ ansible_default_ipv4.gateway }}"  # 192.168.122.1
satellite_dhcp_nameservers: "{{ ansible_dns.nameservers[0] }}"  # 192.168.122.1
satellite_dhcp_domain: "{{ ansible_domain }}"  # example.com
satellite_partition_table_name: "Kickstart default"
satellite_operatingsystem: "RedHat 7.7"
# yamllint disable-line rule:line-length
satellite_kickstart_repository: "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.7"

satellite_host_collections:
  - name: KVMHOSTS_HC
    description: "physical KVM servers"

satellite_content_views:
  - name: RHEL7Ansible_CV
    repositories:
      # yamllint disable-line rule:line-length
      - name: "Red Hat Ansible Engine 2.8 RPMs for Red Hat Enterprise Linux 7 Server x86_64"
        product: "Red Hat Ansible Engine"

  - name: RHEL7SatTools_CV
    repositories:
      - name: "Red Hat Satellite Tools 6.7 for RHEL 7 Server RPMs x86_64"
        product: "Red Hat Enterprise Linux Server"

  - name: RHEL7Server_CV
    repositories:
      - name: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
        product: "Red Hat Enterprise Linux Server"
      - name: "{{ satellite_kickstart_repository }}"
        product: "Red Hat Enterprise Linux Server"

  - name: RHEL7Extras_CV
    repositories:
      - name: "Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64"
        product: "Red Hat Enterprise Linux Server"

  - name: RHEL7Optional_CV
    repositories:
      # yamllint disable-line rule:line-length
      - name: "Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server"
        product: "Red Hat Enterprise Linux Server"

  - name: RHEL7SC_CV
    repositories:
      # yamllint disable-line rule:line-length
      - name: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server x86_64 7Server"
        product: "Red Hat Software Collections (for RHEL Server)"

satellite_composite_content_views:
  - name: RHEL7_KVM_CCV
    components:
      - content_view: RHEL7Server_CV
        latest: true
      - content_view: RHEL7Ansible_CV
        latest: true
      - content_view: RHEL7Extras_CV
        latest: true
      - content_view: RHEL7Optional_CV
        latest: true
      - content_view: RHEL7SatTools_CV
        latest: true

satellite_activation_keys:
  - name: KVM_AK
    lifecycle_environment: "{{ satellite_prod_lifecycle_env }}"
    content_view: RHEL7_KVM_CCV
    host_collections:
      - KVMHOSTS_HC
    subscriptions:
      # yamllint disable-line rule:line-length
      - name: "Red Hat Enterprise Linux Server with Smart Management, Standard (Physical or Virtual Nodes)"
    content_overrides:
      - label: rhel-7-server-ansible-2.8-rpms
        override: enabled
      - label: rhel-7-server-extras-rpms
        override: enabled
      - label: rhel-7-server-optional-rpms
        override: enabled
      - label: rhel-7-server-satellite-tools-{{ satellite_version }}-rpms
        override: enabled
    auto_attach: true
    release_version: 7Server
    service_level: Standard

satellite_subnets:
  - name: "{{ satellite_mgmtsubnet }}"
    description: "{{ satellite_mgmtsubnet }}"
    locations:
      - "{{ satellite_location }}"
    organizations:
      - "{{ satellite_organization }}"
    network: "{{ satellite_network }}"
    mask: "{{ satellite_mask }}"
    gateway: "{{ satellite_dhcp_gateway }}"
    from_ip: "{{ satellite_dhcp_fromip }}"
    to_ip: "{{ satellite_dhcp_toip }}"
    domains:
      - "{{ satellite_domain }}"
    boot_mode: "DHCP"
    ipam: "DHCP"
    dhcp_proxy: "{{ satellite_fqdn }}"
    discovery_proxy: "{{ satellite_fqdn }}"
    httpboot_proxy: "{{ satellite_fqdn }}"
    tftp_proxy: "{{ satellite_fqdn }}"
    remote_execution_proxy: "{{ satellite_fqdn }}"
    server_url: "{{ satellite_server_url }}"

  - name: "DMZ_inside"
    description: "10.1.19.0"
    locations:
      - "{{ satellite_location }}"
    organizations:
      - "{{ satellite_organization }}"
    network: "10.1.19.0"
    mask: "255.255.255.0"
    gateway: "10.1.19.1"
    domains:
      - "{{ satellite_domain }}"
    boot_mode: "DHCP"
    ipam: "DHCP"
    dns_proxy: "{{ satellite_fqdn }}"
    state: present

satellite_domains:
  - name: "{{ satellite_domain }}"
    description: "{{ satellite_domain }}"
    locations:
      - "{{ satellite_location }}"
    organizations:
      - "{{ satellite_organization }}"
    state: present

satellite_hostgroups:
  - name: "BASELINE"
    description: "BASELINE"
    architecture: "{{ satellite_server_basearch }}"
    operatingsystem: "{{ satellite_operatingsystem }}"
    lifecycle_environment: "{{ satellite_prod_lifecycle_env }}"
    content_source: "{{ satellite_fqdn }}"
    content_view: 'RHEL7Server_CV'
    kickstart_repository: "{{ satellite_kickstart_repository }}"
    ptable: "{{ satellite_partition_table_name }}"
    environment: "production"
    organization: "{{ satellite_organization }}"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"
    domain: "{{ satellite_domain }}"
    subnet: "{{ satellite_mgmtsubnet }}"
    parameters:
      - name: allowusbstorage
        value: false
      - name: pass_max_days
        value: 60
      - name: pass_min_days
        value: 1
      - name: pass_min_len
        value: 15
    state: present

  - name: "VM"
    parent: "BASELINE"
    organization: "{{ satellite_organization }}"
    state: present

  - name: "KVM"
    parent: "BASELINE"
    organization: "{{ satellite_organization }}"
    state: present

  - name: "SOMEAPP"
    parent: "BASELINE/VM/SOMEAPP"
    organization: "{{ satellite_organization }}"
    state: present
