- name: Manifest | Pull down manifest
  get_url:
    url: >-
      https://subscription.rhsm.redhat.com/subscription/consumers/
      {{ manifest_uuid }}/export
    username: "{{ satellite_rhn_user }}"
    password: "{{ satellite_rhn_password }}"
    dest: /opt/satellite_manifest.zip
    validate_certs: no
  when: rhn_connect != 'disconnect'

- name: Manifest | Copy manifest from local system to remote target
  copy:
    src: "{{ satellite_manifest }}"
    dest: /opt/satellite_manifest.zip
    owner: root
    group: root
    mode: 0640
  when: rhn_connect == 'disconnect'

- name: Manifest | Upload the manifest
  theforeman.foreman.katello_manifest:
    username: "{{ satellite_rhn_user }}"
    password: "{{ satellite_rhn_password }}"
    server_url: "{{ satellite_server_url }}"
    organization: "{{ satellite_initial_organization }}"
    state: present
    manifest_path: "/opt/satellite_manifest.zip"
