---
- name: Pull down manifest
  get_url:
    url: https://subscription.rhsm.redhat.com/subscription/consumers/{{ manifest_uuid }}/export
    username: "{{ satellite.rhn_user }}"
    password: "{{ satellite.rhn_password }}"
    dest: /opt/satellite_manifest.zip
    validate_certs: no
  when: rhn_connect != 'disconnect'

- name: Copy manifest from local system to remote target
  copy:
    src: "{{ satellite.manifest }}"
    dest: /opt/satellite_manifest.zip
    owner: root
    group: root
    mode: 0640
  when: rhn_connect == 'disconnect'

- name: "Upload the manifest"
  theforeman.foreman.katello_manifest:
    username: "{{ satellite.rhn_user }}"
    password: "{{ satellite.rhn_password }}"
    server_url: "{{ satellite.server_url }}"
    organization: "{{ satellite.initial_organization }}"
    state: present
    manifest_path: "/opt/satellite_manifest.zip"
