- name: satellite_custom_certs | Validate custom certificate bundle
  shell: >-
    katello-certs-check -c {{ satellite_certs_server_cert }}
    -p {{ satellite_certs_server_key }}
    -b {{ satellite_certs_server_ca_cert }}
  register: check_certs
  failed_when: ("[FAIL]" in check_certs.stdout)

- name: satellite_custom_certs | Install custom Satellite certificates
  shell: >-
    satellite-installer
    --certs-server-cert {{ satellite_certs_server_cert }}
    --certs-server-key {{ satellite_certs_server_key }}
    --certs-server-ca-key {{ satellite_certs_server_ca_cert }}
  register: update_satellite_with_custom_certs
  when: ("Validation succeeded" in check_certs.stdout)
