- name: Enabling repos | Check to see if localhost is running Satellite
  shell: command -v hammer >/dev/null 2>&1
  register: is_hammer_exist

- name: Enabling repos | Checking pulp directory is owned by apache
  file:
    path: /var/lib/pulp
    owner: apache
    group: apache
    mode: '0755'

- name: "Enable RHEL repositories with label that need releasever"
  theforeman.foreman.katello_repository_set:
    username: "{{ lookup('env','FOREMAN_USER') }}"
    password: "{{ lookup('env','FOREMAN_PASSWORD') }}"
    server_url: "https://{{ ansible_fqdn }}"
    organization: "{{ foreman_initial_organization }}"
    label: "{{ item.label }}"
    repositories:
      - releasever: "{{ server_releasever }}"
        basearch: "{{ server_basearch }}"
    state: enabled
  with_items:
    - "{{ red_hat_repositories_releasever }}"

- name: "Enable RHEL repositories with label"
  theforeman.foreman.katello_repository_set:
    username: "{{ lookup('env','FOREMAN_USER') }}"
    password: "{{ lookup('env','FOREMAN_PASSWORD') }}"
    server_url: "https://{{ ansible_fqdn }}"
    organization: "{{ foreman_initial_organization }}"
    label: "{{ item.label }}"
    repositories:
      - basearch: "{{ server_basearch }}"
    state: enabled
  with_items:
    - "{{ red_hat_repositories }}"
