- name: Get all repositories
  theforeman.foreman.foreman_search_facts:
    username: "{{ lookup('env','FOREMAN_USER') }}"
    password: "{{ lookup('env','FOREMAN_PASSWORD') }}"
    server_url: "https://{{ ansible_fqdn }}"
    resource: repositories
  register: repositories

- name: Kick off repository Sync tasks
  theforeman.foreman.katello_sync:
    username: "{{ lookup('env','FOREMAN_USER') }}"
    password: "{{ lookup('env','FOREMAN_PASSWORD') }}"
    server_url: "https://{{ ansible_fqdn }}"
    product: "{{ item.product.name }}"
    repository: "{{ item.name }}"
    organization: "{{ foreman_initial_organization }}"
  loop: "{{ repositories.resources }}"
  when: item.url  # Not all repositories have a URL
  async: 999999
  poll: 0
  register: repo_sync_sleeper

- name: Wait until all Syncs have finished
  async_status:
    jid: "{{ repo_sync_sleeper_item.ansible_job_id }}"
  loop: "{{ repo_sync_sleeper.results }}"
  loop_control:
    loop_var: repo_sync_sleeper_item
  # Skip items that were skipped in the previous task
  when: repo_sync_sleeper_item.ansible_job_id is defined
  register: async_job_result
  until: async_job_result.finished
  retries: 999
  delay: 10
