- name: Repo Sync | Get all repositories
  oasis_roles.satellite.foreman_search_facts:
    username: "{{ satellite_rhn_user }}"
    password: "{{ satellite_rhn_password }}"
    server_url: "{{ satellite_server_url }}"
    resource: repositories
  register: repositories

- name: Repo Sync | Kick off repository Sync tasks
  oasis_roles.satellite.katello_sync:
    username: "{{ satellite_rhn_user }}"
    password: "{{ satellite_rhn_password }}"
    server_url: "{{ satellite_server_url }}"
    product: "{{ item.product.name }}"
    repository: "{{ item.name }}"
    organization: "{{ satellite_initial_organization }}"
  loop: "{{ repositories.resources }}"
  when: item.url  # Not all repositories have a URL
  async: 999999
  poll: 0
  register: repo_sync_sleeper

- name: Repo Sync | Wait until all Syncs have finished
  async_status:
    jid: "{{ repo_sync_sleeper_item.ansible_job_id }}"
  loop: "{{ repo_sync_sleeper.results }}"
  loop_control:
    loop_var: repo_sync_sleeper_item
  # Skip items that were skipped in the previous task
  when: repo_sync_sleeper_item.ansible_job_id is defined
  register: async_job_result
  until: async_job_result.finished
  retries: 999
  delay: 10
