- name: etc hosts | add VM hostname / ip
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ satellite_hostname }}'
    line: "{{ satellite_hostip }}   {{ satellite_fqdn }} {{ satellite_hostname }}"
  when: satellite_hostip is defined
