- name: etc hosts | add VM hostname / ip
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ satellite_hostname }}'
    line: "{{ satellite_hostip }} {{ satellite_hostname }}.{{ satellite_domain }} {{ satellite_hostname }}"
  when: satellite_hostip is defined
