- name: Patch system | yum-clean-metadata
  command: yum clean all
  args:
    warn: no

- name: Patch system | Remove not needed packages
  package:
    name: iwl7265-firmware
    state: absent

- name: Patch system | Checking if update is required
  shell: yum -q check-update > /dev/null
  register: patch_lvl
  failed_when: patch_lvl.rc not in [100,0]
  become: yes

- name:
  block:
  - name: Patch system | Patching the system
    package:
      name: "*"
      state: latest

  - name: Patch system | rebooting on new kernel
    reboot:

  - name: >-
      Patch system | Wait 600 seconds for target connection to become
      reachable/usable
    wait_for_connection:

  when: patch_lvl.rc == 100

- name: Patch system | refreshing ansible facts
  setup:
