- name: Install | Check whether Satellite is installed using
        foreman-maintain service status
  shell: foreman-maintain service status > /dev/null
  register: check_satellite_installed
  failed_when: check_satellite_installed.rc not in [127,1,0]
  changed_when: false

- name:
  block:
  - name: Install | Yum install the packages required for satellite
    package:
      name: "{{ satellite_yum_packages }}"
      state: present

  - name: Install | Satellite if it is not installed
    command: >-
       satellite-installer --scenario satellite {{ satellite_options }}

  - name: Move performance tuning yaml to
      /etc/foreman-installer/custom-hiera.yaml
    copy:
      src: files/custom-hiera.yaml
      dest: /etc/foreman-installer/custom-hiera.yaml
      owner: root
      group: root

  - name: Install | Activation of the performance tuning
    command: satellite-installer

  when: check_satellite_installed.rc == 127
