- name: Satellite Settings | Common Settings
  theforeman.foreman.foreman_setting:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - "{{ satellite_settings }}"

- name: Satellite Settings | Disconnected Settings
  theforeman.foreman.foreman_setting:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    name: "content_disconnected"
    value: "true"
  when: rhn_connect == 'disconnect'
