- name: Main | Configure firewalld
  import_tasks: 1_firewalld_config.yml

- name: Main | enable Foreman ansible modules
  import_tasks: 2_foreman_ansible.yml

- name: Main | Storage Config
  import_tasks: 3_storage_config.yml

- name: Main | Enable FIPS
  import_tasks: 4_fips.yml

- name: Main | Satellite install
  import_tasks: 5_satellite_install.yml

- name: Main | Configuring Satellite 6 server
  import_tasks: 6_satellite_settings.yml

- name: Main | Uploading Manifest
  import_tasks: 7_manifest.yml

- name: Main | Enabling repos
  import_tasks: 8_enablerepos.yml

- name: Main | Synchronizing repos
  import_tasks: 9_repo_sync.yml
