- name: Host Collections
  import_tasks: host_collections.yml

- name: Content Views
  import_tasks: content_view_config.yml

- name: Activations Keys
  import_tasks: activation_key.yml

- name: Sync Plan
  import_tasks: sync_plan.yml

#- name: Create infrastructure necessary for openscap
#  include_tasks: openscap_config.yml
#  loop: "{{ hostgroup_config }}"
#  loop_control:
#     loop_var: hostgroup
